// flow-typed signature: eea15427541ffda05f1bef7ff0e78ca6
// flow-typed version: <<STUB>>/@thewickedwebdev/components_v0.0.6/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@thewickedwebdev/components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@thewickedwebdev/components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@thewickedwebdev/components/dist/index.cjs' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/dist/index.cjs.min' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/dist/index.esm' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/dist/index.esm.min' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/rollup.config' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/Article/Article.test' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/Article' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/Image' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/LazyLoad' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/LazyLoad/LazyLoad.test' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/Link' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/List' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/List/List' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/List/List.stories' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/List/List.test' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/Meta/favicon' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/Meta' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/Meta/Meta.test' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/Meta/og' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/Page' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/Page/Page' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/Section' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/Section/Section.test' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/Tag' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/Tag/Tag' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/Tag/Tag.stories' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/TagList' {
  declare module.exports: any;
}

declare module '@thewickedwebdev/components/src/TagList/TagList' {
  declare module.exports: any;
}

// Filename aliases
declare module '@thewickedwebdev/components/dist/index.cjs.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/dist/index.cjs'>;
}
declare module '@thewickedwebdev/components/dist/index.cjs.min.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/dist/index.cjs.min'>;
}
declare module '@thewickedwebdev/components/dist/index.esm.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/dist/index.esm'>;
}
declare module '@thewickedwebdev/components/dist/index.esm.min.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/dist/index.esm.min'>;
}
declare module '@thewickedwebdev/components/rollup.config.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/rollup.config'>;
}
declare module '@thewickedwebdev/components/src/Article/Article.test.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Article/Article.test'>;
}
declare module '@thewickedwebdev/components/src/Article/index' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Article'>;
}
declare module '@thewickedwebdev/components/src/Article/index.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Article'>;
}
declare module '@thewickedwebdev/components/src/Image/index' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Image'>;
}
declare module '@thewickedwebdev/components/src/Image/index.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Image'>;
}
declare module '@thewickedwebdev/components/src/index' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src'>;
}
declare module '@thewickedwebdev/components/src/index.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src'>;
}
declare module '@thewickedwebdev/components/src/LazyLoad/index' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/LazyLoad'>;
}
declare module '@thewickedwebdev/components/src/LazyLoad/index.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/LazyLoad'>;
}
declare module '@thewickedwebdev/components/src/LazyLoad/LazyLoad.test.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/LazyLoad/LazyLoad.test'>;
}
declare module '@thewickedwebdev/components/src/Link/index' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Link'>;
}
declare module '@thewickedwebdev/components/src/Link/index.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Link'>;
}
declare module '@thewickedwebdev/components/src/List/index' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/List'>;
}
declare module '@thewickedwebdev/components/src/List/index.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/List'>;
}
declare module '@thewickedwebdev/components/src/List/List.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/List/List'>;
}
declare module '@thewickedwebdev/components/src/List/List.stories.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/List/List.stories'>;
}
declare module '@thewickedwebdev/components/src/List/List.test.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/List/List.test'>;
}
declare module '@thewickedwebdev/components/src/Meta/favicon.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Meta/favicon'>;
}
declare module '@thewickedwebdev/components/src/Meta/index' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Meta'>;
}
declare module '@thewickedwebdev/components/src/Meta/index.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Meta'>;
}
declare module '@thewickedwebdev/components/src/Meta/Meta.test.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Meta/Meta.test'>;
}
declare module '@thewickedwebdev/components/src/Meta/og.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Meta/og'>;
}
declare module '@thewickedwebdev/components/src/Page/index' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Page'>;
}
declare module '@thewickedwebdev/components/src/Page/index.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Page'>;
}
declare module '@thewickedwebdev/components/src/Page/Page.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Page/Page'>;
}
declare module '@thewickedwebdev/components/src/Section/index' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Section'>;
}
declare module '@thewickedwebdev/components/src/Section/index.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Section'>;
}
declare module '@thewickedwebdev/components/src/Section/Section.test.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Section/Section.test'>;
}
declare module '@thewickedwebdev/components/src/Tag/index' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Tag'>;
}
declare module '@thewickedwebdev/components/src/Tag/index.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Tag'>;
}
declare module '@thewickedwebdev/components/src/Tag/Tag.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Tag/Tag'>;
}
declare module '@thewickedwebdev/components/src/Tag/Tag.stories.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/Tag/Tag.stories'>;
}
declare module '@thewickedwebdev/components/src/TagList/index' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/TagList'>;
}
declare module '@thewickedwebdev/components/src/TagList/index.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/TagList'>;
}
declare module '@thewickedwebdev/components/src/TagList/TagList.js' {
  declare module.exports: $Exports<'@thewickedwebdev/components/src/TagList/TagList'>;
}
