// flow-typed signature: 733c1520f6a26e4fbc32f4d067759aae
// flow-typed version: <<STUB>>/@loadable/webpack-plugin_v^5.12.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@loadable/webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@loadable/webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@loadable/webpack-plugin/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@loadable/webpack-plugin/lib/index' {
  declare module.exports: $Exports<'@loadable/webpack-plugin/lib'>;
}
declare module '@loadable/webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'@loadable/webpack-plugin/lib'>;
}
