// flow-typed signature: c15d82518e9e40f9cabee6ea8e36c708
// flow-typed version: <<STUB>>/jest-css-modules_v^2.1.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-css-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-css-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-css-modules/tests/classNameList' {
  declare module.exports: any;
}

declare module 'jest-css-modules/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-css-modules/index' {
  declare module.exports: $Exports<'jest-css-modules'>;
}
declare module 'jest-css-modules/index.js' {
  declare module.exports: $Exports<'jest-css-modules'>;
}
declare module 'jest-css-modules/tests/classNameList.js' {
  declare module.exports: $Exports<'jest-css-modules/tests/classNameList'>;
}
declare module 'jest-css-modules/tests/test.js' {
  declare module.exports: $Exports<'jest-css-modules/tests/test'>;
}
