// flow-typed signature: 9d3bf9be6f625ce615b9862d2c38c958
// flow-typed version: <<STUB>>/jest-transform-stub_v^2.0.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-transform-stub'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-transform-stub' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jest-transform-stub/index' {
  declare module.exports: $Exports<'jest-transform-stub'>;
}
declare module 'jest-transform-stub/index.js' {
  declare module.exports: $Exports<'jest-transform-stub'>;
}
