// flow-typed signature: 95734fa3f6378d11f8ada43eed7dead8
// flow-typed version: <<STUB>>/pdfkit_v^0.11.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pdfkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pdfkit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pdfkit/js/pdfkit.es5' {
  declare module.exports: any;
}

declare module 'pdfkit/js/pdfkit.esnext' {
  declare module.exports: any;
}

declare module 'pdfkit/js/pdfkit' {
  declare module.exports: any;
}

declare module 'pdfkit/js/pdfkit.standalone' {
  declare module.exports: any;
}

declare module 'pdfkit/js/virtual-fs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pdfkit/js/pdfkit.es5.js' {
  declare module.exports: $Exports<'pdfkit/js/pdfkit.es5'>;
}
declare module 'pdfkit/js/pdfkit.esnext.js' {
  declare module.exports: $Exports<'pdfkit/js/pdfkit.esnext'>;
}
declare module 'pdfkit/js/pdfkit.js' {
  declare module.exports: $Exports<'pdfkit/js/pdfkit'>;
}
declare module 'pdfkit/js/pdfkit.standalone.js' {
  declare module.exports: $Exports<'pdfkit/js/pdfkit.standalone'>;
}
declare module 'pdfkit/js/virtual-fs.js' {
  declare module.exports: $Exports<'pdfkit/js/virtual-fs'>;
}
