// flow-typed signature: eb723d6251c25fd57013e02f8e52f00c
// flow-typed version: <<STUB>>/string-strip-html_v^4.3.16/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string-strip-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'string-strip-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'string-strip-html/dist/string-strip-html.cjs' {
  declare module.exports: any;
}

declare module 'string-strip-html/dist/string-strip-html.esm' {
  declare module.exports: any;
}

declare module 'string-strip-html/dist/string-strip-html.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'string-strip-html/dist/string-strip-html.cjs.js' {
  declare module.exports: $Exports<'string-strip-html/dist/string-strip-html.cjs'>;
}
declare module 'string-strip-html/dist/string-strip-html.esm.js' {
  declare module.exports: $Exports<'string-strip-html/dist/string-strip-html.esm'>;
}
declare module 'string-strip-html/dist/string-strip-html.umd.js' {
  declare module.exports: $Exports<'string-strip-html/dist/string-strip-html.umd'>;
}
