// flow-typed signature: a62abc11fffeb83e94b17ca9dc51eb50
// flow-typed version: <<STUB>>/webpack-clean-obsolete-chunks_v^0.4.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-clean-obsolete-chunks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-clean-obsolete-chunks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-clean-obsolete-chunks/index' {
  declare module.exports: $Exports<'webpack-clean-obsolete-chunks'>;
}
declare module 'webpack-clean-obsolete-chunks/index.js' {
  declare module.exports: $Exports<'webpack-clean-obsolete-chunks'>;
}
