// flow-typed signature: f3946fed787d48f4d9c544e7bdadcb26
// flow-typed version: <<STUB>>/webpack-plugin-replace_v^1.2.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-plugin-replace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-plugin-replace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-plugin-replace/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-plugin-replace/lib/index' {
  declare module.exports: $Exports<'webpack-plugin-replace/lib'>;
}
declare module 'webpack-plugin-replace/lib/index.js' {
  declare module.exports: $Exports<'webpack-plugin-replace/lib'>;
}
