// flow-typed signature: 291b5622d89a493c2729ee16bac1d053
// flow-typed version: <<STUB>>/@storybook/addon-jest_v^5.3.17/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-jest/dist/components/Message' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/dist/components/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/dist/components/Result' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/dist/hoc/provideJestResult' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/dist/shared' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/dist/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addon-jest/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-jest/dist/components/Message.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/dist/components/Message'>;
}
declare module '@storybook/addon-jest/dist/components/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/dist/components/Panel'>;
}
declare module '@storybook/addon-jest/dist/components/Result.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/dist/components/Result'>;
}
declare module '@storybook/addon-jest/dist/hoc/provideJestResult.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/dist/hoc/provideJestResult'>;
}
declare module '@storybook/addon-jest/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-jest/dist'>;
}
declare module '@storybook/addon-jest/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/dist'>;
}
declare module '@storybook/addon-jest/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/dist/register'>;
}
declare module '@storybook/addon-jest/dist/shared.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/dist/shared'>;
}
declare module '@storybook/addon-jest/dist/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/dist/typings.d'>;
}
declare module '@storybook/addon-jest/register.js' {
  declare module.exports: $Exports<'@storybook/addon-jest/register'>;
}
